services:
  db:
    image: postgres:15-alpine
    container_name: stellarstay_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    networks:
      - stellarstay_net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: stellarstay_zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - stellarstay_net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: stellarstay_kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - stellarstay_net

  prometheus:
    image: prom/prometheus:latest
    container_name: stellarstay_prometheus
    volumes:
      - ./prometheus.docker.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - stellarstay_net

  app:
    build: .
    container_name: stellarstay_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      SERVER_PORT: ${SERVER_PORT:-8080}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_RESERVATIONS: ${KAFKA_TOPIC_RESERVATIONS}
    ports:
      - "8080:8080"
    depends_on:
      - db
      - kafka
      - prometheus
    networks:
      - stellarstay_net
    volumes:
      - ./target:/app/target

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka_ui
    ports:
      - "8081:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - stellarstay_net

volumes:
  db_data:

networks:
  stellarstay_net:
    driver: bridge

# Usage:
# 1. Copy .env.example to .env.prod and adjust values as needed.
# 2. Run: docker compose -f docker-compose.yml --env-file .env.prod up -d
#
# This will start the dependencies and the app service.
# All configuration is managed via environment variables.
