version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: stellarstay_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - stellarstay_net

  app:
    build: .
    container_name: stellarstay_app
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${SPRING_JPA_HIBERNATE_DDL_AUTO:-update}
      SERVER_PORT: ${SERVER_PORT:-8080}
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - stellarstay_net

volumes:
  db_data:

networks:
  stellarstay_net:
    driver: bridge

# Usage:
# 1. Copy .env to .env and adjust values as needed.
# 2. Run: docker-compose up --build
#
# All configuration is managed via environment variables.
# For local development, set DB_HOST=localhost in .env and run the app outside Docker.
