version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: stellarstay_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - stellarstay_net

  # Add other dependencies here (e.g., redis, rabbitmq) as needed for development

volumes:
  db_data:

networks:
  stellarstay_net:
    driver: bridge

# Usage:
# 1. Copy .env.example to .env and adjust values as needed.
# 2. Run: docker compose -f docker-compose.dev.yml up -d
#
# This will start only the dependencies (no app service).
# Run the Spring Boot app from IntelliJ or your IDE.

